version: '2'
services:
  proxy:
    extends:
      file: ./proxy/docker-compose.yml
      service: nginx-proxy
  webserver:
    extends:
      file: ./nginx/docker-compose.yml
      service: nginx
    environment:
      - VIRTUAL_HOST=experiments.nmrony.local,nmrony.local,itc-blog.nmrony.local
  php:
    extends:
      file: ./nginx/docker-compose.yml
      service: php
  pma:
    extends:
      file: ./pma/docker-compose.yml
      service: pma
    ports:
      - 8080:80
    environment:
      - VIRTUAL_HOST=pma.nmrony.local
      - PMA_HOSTS=mysql-dev,test_mariadb
  mysql-dev:
    extends:
      file: ./mariadb/docker-compose.yml
      service: mariadb
    volumes:
      - ${DEV_ZONE}/storage/mysql-common:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nmrony
