version: '2'
services:
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    ports:
      - 80
    depends_on:
      - mariadb
    environment:
      - VIRTUAL_HOST=pma.nmrony.docker
