nginx:
  image: nginx:stable-alpine
  container_name: nginx
  restart: always
  links:
    - php
  volumes:
    - ./html:/usr/share/nginx/html:ro
    - ./sites-enabled:/etc/nginx/sites-enabled:ro
    - ./sites-available:/etc/nginx/sites-available:ro
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  environment:
    - VIRTUAL_HOST=experiments.nmrony.docker,nmrony.docker
php:
  image: yavin/alpine-php-fpm
  container_name: php
  restart: always
  volumes:
    - ./html:/usr/share/nginx/html:ro
  ports:
    - 9000:9000
