version: '2'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    volumes:
      - ${DEV_ZONE}/projects:/usr/share/nginx/html
      - ${DEV_ZONE}/settings/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
      - ${DEV_ZONE}/settings/nginx/sites-available:/etc/nginx/sites-available:ro
      - ${DEV_ZONE}/settings/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - ronsvpn
  php:
    image: yavin/alpine-php-fpm
    container_name: php
    restart: always
    volumes:
      - ${DEV_ZONE}/projects:/usr/share/nginx/html:ro
    ports:
      - 9000:9000
    networks:
      - ronsvpn
networks:
  ronsvpn:
    external: true

